# Generated by Django 4.1.2 on 2025-12-31 10:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("memberships", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="membershiprequest",
            unique_together=set(),
        ),
    ]
